pretrained_path: base_model
train_manifest: data/occidental/train.jsonl
val_manifest: data/occidental/valid.jsonl
sample_rate: 44100
batch_size: 16
grad_accum_steps: 1  # Gradient accumulation steps, >1 can increase effective batch size without increasing memory
num_workers: 4
num_iters: 21000
log_interval: 10
valid_interval: 1000
save_interval: 3000
learning_rate: 0.00001 
weight_decay: 0.01
warmup_steps: 100
max_steps: 21000
max_batch_tokens: 8192  # Example: single batch can have at most 16k tokens, with batch_size=4, each sample can have at most 4096 tokens
save_path: models/finetune_all_occidental
tensorboard: logs/finetune_all_occidental
lambdas:
  loss/diff: 1.0
  loss/stop: 1.0
